
drop database dbHospital 
go
create database dbHospital 
go
use dbHospital
go
 
create table Paciente.PACIENTE 
(
CODPAC  INT NOT NULL IDENTITY(1,1) ,
NOMPAC VARCHAR (120) NOT NULL,
APEPATPAC VARCHAR (120) NOT NULL,
APEMATPAC VARCHAR (120)	NOT NULL,
FECNACPAC DATE NOT NULL,
SEXPAC CHAR (1)NOT NULL,
DENIPAC CHAR(8)NOT NULL,
TELEFPAC VARCHAR(9)NULL,
EMAILPAC VARCHAR (100) NULL,
DOMPAC VARCHAR (120)NOT NULL,
UBIGEOPAC CHAR (6)NOT NULL,
FECREGPAC DATETIME NULL ,
OBSERVPAC VARCHAR (250) NULL
CONSTRAINT PK_CODPAC
PRIMARY KEY (CODPAC)
)
GO

CREATE TABLE Historia.HiSTORIA
(
CODHIST INT NOT NULL IDENTITY(1,1) ,
FECHIST DATETIME NOT NULL,
OBSHIST	VARCHAR (1800) NOT NULL
CONSTRAINT CODHIST
PRIMARY KEY (CODHIST)
)
GO

CREATE TABLE Paciente.HISTORIA_PACIENTE 
(
CODHIST	INT	NOT NULL IDENTITY(1,1),
CODPAC	INT NOT NULL,
CODMED	INT NOT NULL
CONSTRAINT CODHIST
PRIMARY KEY (CODHIST,CODPAC,CODMED)
)
GO

CREATE TABLE Historia.TURNO
(
CODTUR INT NOT NULL IDENTITY(1,1),
FECTUR DATETIME NOT NULL,
ESTTUR DATETIME NOT NULL,
OBSTUR VARCHAR (500)
 )
 GO


CREATE TABLE Paciente.TURNO_PACIENTE
(
CODTUR  INT NOT NULL IDENTITY(1,1),
CODPAC INT NOT NULL,
CODMED INT NOT NULL,
CONSTRAINT PK_CODTUR
PRIMaRY KEY(CODTUR,CODPAC,CODMED)
)
GO

CREATE TABLE Paciente.UBIGEO 
(
CODUBI CHAR (6) NOT NULL ,
DISTUB VARCHAR (60) NOT NULL, 
PROVUB VARCHAR (60) NOT NULL,
PAISUB	VARCHAR (60) NOT NULL
CONSTRAINT CODUBI
PRIMARY KEY (CODUBI)
)
GO
CREATE TABLE Medico.ESPECIALIDAD
(
CODESP INT NOT NULL IDENTITY(1,1) ,
NOMESP VARCHAR (80) NOT NULL,
OBSESP VARCHAR (100) NULL
CONSTRAINT CODESP
PRIMARY KEY (CODESP)
)
GO

CREATE TABLE Medico.MEDICO
(
CODMED  INT NOT NULL IDENTITY(1,1),
NOMMED VARCHAR (120) NOT NULL,
APEPATMED VARCHAR (120) NOT NULL,
APEMATMED VARCHAR (120) NOT NULL, 
FECNAC DATE NOT NULL,
SEXMED CHAR (1) NOT NULL,
DENIMED CHAR (8) NOT NULL, 
TELEFMED VARCHAR (9) NULL,
EMAILMED VARCHAR  (120)  NULL, 
DOMMED VARCHAR (120) NOT NULL,
UBIGEOMED CHAR (6)  NULL,
FECREGMED DATETIME  NULL
CONSTRAINT CODMED
PRIMARY KEY (CODMED)
)
GO 

CREATE TABLE Medico.MEDICO_ESPECIALIDAD
(
CODMED INT NOT NULL,
CODESP INT NOT NULL,
DESCESP VARCHAR (1000) 
CONSTRAINT PK_CODMED
PRIMARY KEY (CODMED,CODESP)
)
GO

ALTER TABLE paciente.PACIENTE
add CONSTRAINT FK_PACIENTE_UBIGEO
foreign key (UBIGEOPAC) REFERENCES Paciente.Ubigeo(CODUBI)
GO

ALTER TABLE medico.MEDICO
add CONSTRAINT FK_MEDICO_ESPECIALIDAD_MEDICO
foreign key (CODMED) REFERENCES Medico.ESPECIALIDAD(CODMED)
GO

ALTER TABLE medico.ESPECIALIDAD
add CONSTRAINT FK_MEDICO_ESPECIALIDAD_ESPECIALIDAD
foreign key (CODESP) REFERENCES Medico.MEDICO(CODESP)
GO

ALTER TABLE historia.TURNO
add CONSTRAINT FK_TURNO_PACIENTE_TURNO
foreign key (CODTUR) REFERENCES paciente.TURNO_PACIENTE
GO

ALTER TABLE paciente.PACIENTE
add CONSTRAINT FK_TURNO_PACIENTE_PACIENTE
foreign key (CODPAC) REFERENCES Paciente.TURNO_PACIENTE
GO